# Generated by Django 6.0.3 on 2026-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointments_field',
            new_name='appointments_status',
        ),
        migrations.AddField(
            model_name='appointments',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
